name: Build

on:
  push:
    branches-ignore:
      - 'abandoned-*'
  schedule:
    # Daily at 2AM
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'

permissions:
  checks: write
  pull-requests: write

env:
  cache-name: docker-cache-17

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "mahoney266/lidalia-world-gha"
          install: true

      - uses: docker/build-push-action@v5
        with:
          target: build-output
          outputs: 'type=cacheonly,type=local,dest=build'

      - uses: docker/build-push-action@v5
        with:
          outputs: 'type=cacheonly'

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Test Results
          junit_files: |
            build/test-results/**/*.xml

      - name: Archive build results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-reports
          path: build/reports

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: jars
          path: build/libs
