name: Build

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: Whether or not to run in a cached docker environment
        required: false
        default: true
  push:
    branches-ignore:
      - 'abandoned-*'
  schedule:
    # Daily at 2AM
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4

      - uses: Mahoney-github-actions/gradle-build-output/actions/prepare-docker-build@v2
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.use-cache)
        with:
          dockerhub_token: ${{ secrets.DOCKER_PAT }}

      - name: Set GRADLE_ARGS based on debug mode
        id: set_gradle_args
        if: ${{ runner.debug == '1' }}
        run: |
          echo "gradle_args=--info --stacktrace" >> $GITHUB_OUTPUT
          echo "BUILDKIT_PROGRESS=plain" >> $GITHUB_ENV
          echo "PROGRESS_NO_TRUNC=1" >> $GITHUB_ENV

      - run: ./build.sh --build-arg "GRADLE_ARGS=${{ steps.set_gradle_args.outputs.gradle_args}}" \

      - uses: Mahoney-github-actions/gradle-build-output@v2
        if: always()
