name: Build

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: Whether or not to run in a cached docker environment
        required: false
        default: true
  push:
    branches-ignore:
      - 'abandoned-*'
  schedule:
    # Daily at 2AM
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        if: github.event_name == 'push' || inputs.use-cache
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/setup-buildx-action@v3
        if: github.event_name == 'push' || inputs.use-cache
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "mahoney266/lidalia-world-gha"
          install: true

      - name: Set GRADLE_ARGS based on debug mode
        if: ${{ runner.debug == '1' }}
        run: echo "GRADLE_ARGS=--info --stacktrace" >> $GITHUB_ENV

      - run: ./build.sh ${{ env.GRADLE_ARGS }}

      - uses: Mahoney-github-actions/gradle-build-output@v2
        if: always()
