name: Uncached (nightly) Build

on:
  workflow_dispatch:
  schedule:
    # Daily at 2AM
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'

permissions:
  checks: write

jobs:
  uncached-build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - id: gradle-args
        name: Set GRADLE_ARGS based on debug mode
        if: ${{ runner.debug == '1' }}
        run: echo "GRADLE_ARGS=--info --stacktrace" >> $GITHUB_ENV

      - run: ./build.sh ${{ env.GRADLE_ARGS }}

      - uses: Mahoney-github-actions/gradle-build-output@v2
        if: always()
