name: Build

on:
  schedule:
    # Daily at 2AM
    # * is a special character in YAML so you have to quote this string
    - cron: '0 2 * * *'

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v4

      - run: ./build.sh

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Test Results
          junit_files: |
            build/**/test-results/**/*.xml

      - name: Archive build results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build
          path: build

      - name: Archive output
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jars
          path: build/artifacts
